title: Tom's Quest AI
email: tom@tomsquest.com
description: >-
  AI Experiments and Projects
baseurl: ""
url: https://ai.tomsquest.com
domain: ai.tomsquest.com
plugins:
  - jekyll-feed
collections:
  projects:
    output: true
    sort_by: order
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - .idea/
  - README.md
  - LICENSE