title: ai.tomsquest.com
email: tom@tomsquest.com
description: >-
  AI Experiments and Projects
baseurl: ""
url: https://ai.tomsquest.com
domain: ai.tomsquest.com
logo: /assets/images/logo.png
social:
  name: Thomas Queste
  links:
    - https://twitter.com/thomasqueste
    - https://www.linkedin.com/in/thomasqueste
    - https://github.com/tomsquest/
    - https://keybase.io/thomasqueste
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  projects:
    output: true
    sort_by: order
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - .idea/
  - README.md
  - LICENSE